stages:
  - build
  - security_scan_fs
  # - static_analysis
  # - image_build_push
  # - image_scan
  # - deploy

variables:
    TAG: $CI_COMMIT_SHA

build:
  stage: build
  image: gradle:7.5.0-jdk17
  script:
    - echo "Building the Java project..."
    - gradle clean build -x test
  artifacts:
    paths:
      - build/libs/*.jar 
    when: on_success
    access: all
    expire_in: 30 days
  only:
    - dev

security_scan:
  stage: security_scan_fs
  image: 
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - echo "Security scan with Trivy..."
    - trivy fs --exit-code 0 --no-progress --severity HIGH,CRITICAL .
  only:
    - dev
    - stage
    - main

