stages:
  - build
  - security_scan_fs
  - image_build_push
  # - image_scan
  - deploy

variables:
  TAG: $CI_COMMIT_SHORT_SHA

build:
  stage: build
  image: gradle:7.5.0-jdk17
  script:
    - echo "Building the Java project..."
    - gradle clean build -x test
  artifacts:
    paths:
      - build/libs/*.jar 
    when: on_success
    access: all
    expire_in: 30 days
  only:
    - dev
    - stage
    - main


security_scan:
  stage: security_scan_fs
  image: 
    name: aquasec/trivy:latest
    entrypoint: [""]
  cache:
    key: trivy-db
    paths:
      - /root/.cache/trivy/db
  script:
    - echo "Security scan with Trivy..."
    #- if [ ! -f /root/.cache/trivy/db/trivy.db ]; then trivy fs --exit-code 0 --severity LOW,MEDIUM,HIGH,CRITICAL .; else trivy fs --skip-update --exit-code 0 --severity LOW,MEDIUM,HIGH,CRITICAL .; fi
  only:
    - dev
    - stage

image_build_push:
  stage: image_build_push
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE:$TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$TAG"
  only:
    - dev
    - stage
    - main

deploy_to_vm:
  stage: deploy
  image: alpine:latest
  dependencies:
    - build_push
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
    - echo "$ENV_FILE_CONTENT" > .env
  script:
    - ssh $SSH_USER@$SSH_HOST "docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY"
    - ssh $SSH_USER@$SSH_HOST "docker pull $CI_REGISTRY_IMAGE:$TAG"
    - ssh $SSH_USER@$SSH_HOST "docker stop $CI_PROJECT_NAME || true && docker rm $CI_PROJECT_NAME || true"
    - ssh $SSH_USER@$SSH_HOST "docker run -d --env-file=.env --name $CI_PROJECT_NAME -p 8080:8080 $CI_REGISTRY_IMAGE:$TAG"
  only:
    - dev
    - stage
    - prod
