spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: rizvan.memmedov2004@gmail.com
    password: csvk iwsq fcyz xbyu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true