cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS-KEY}
      secret-key: ${AWS_SECRET-KEY}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    s3:
      bucket:
        name: ${AWS_BUCKET-NAME}
